language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
- "pip install -r requirements.txt"
- "python setup.py build install"

# command to run tests
script:
- python setup.py test

deploy:
  provider: pypi
  user: fleming79
  password: Read1MPassword2
  distributions: "bdist_wheel"
  on:
    branch: master